import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";
import fs from "node:fs";
import path from "node:path";

type DeploymentJson = {
  address: string;
  abi: unknown;
};

function readDeploymentJson(deploymentsDir: string, contractName: string): DeploymentJson {
  const filePath = path.join(deploymentsDir, `${contractName}.json`);
  const raw = fs.readFileSync(filePath, "utf-8");
  const parsed = JSON.parse(raw) as DeploymentJson;
  if (!parsed?.address || !parsed?.abi) throw new Error(`Invalid deployment file: ${filePath}`);
  return parsed;
}

function toTsStringLiteral(value: string) {
  return `'${value.replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
}

task("task:sync-ui", "Sync Sepolia deployments (addresses + ABI) into ui/src/config/contracts.ts")
  .addOptionalParam("networkName", "Hardhat-deploy network folder name", "sepolia")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const networkName = String(taskArguments.networkName || "sepolia");
    const root = hre.config.paths.root;

    const deploymentsDir = path.join(root, "deployments", networkName);
    const uiOutFile = path.join(root, "ui", "src", "config", "contracts.ts");

    const ccoin = readDeploymentJson(deploymentsDir, "ConfidentialCoin");
    const staking = readDeploymentJson(deploymentsDir, "SecureAPRStaking");

    const content = `// Auto-generated by \`npx hardhat task:sync-ui --networkName ${networkName}\`
// Source: deployments/${networkName}/*.json
// Do not edit manually.

export const SEPOLIA_CHAIN_ID = 11155111 as const;

export const CCOIN_ADDRESS = ${toTsStringLiteral(ccoin.address)} as const;
export const STAKING_ADDRESS = ${toTsStringLiteral(staking.address)} as const;

export const CCOIN_ABI = ${JSON.stringify(ccoin.abi, null, 2)} as const;
export const STAKING_ABI = ${JSON.stringify(staking.abi, null, 2)} as const;
`;

    fs.mkdirSync(path.dirname(uiOutFile), { recursive: true });
    fs.writeFileSync(uiOutFile, content, "utf-8");

    console.log(`Wrote ${path.relative(root, uiOutFile)}`);
    console.log(`- ConfidentialCoin: ${ccoin.address}`);
    console.log(`- SecureAPRStaking: ${staking.address}`);
  });

